### PR TITLE
Here's a nice "little" example for you.

### PR DESCRIPTION
**Pull request by rdebath**
Before you get too impressed I only translated it!

The other two patches are needed to make it run. The jumps change is a required performance improvement and the comments are so I can say this in the file.

But... I that comment format is going to be nasty with tabs!

BTW: The conversion from BF probably counts as a Turning completeness proof, if there was any doubt.

### CODE REVIEW

**Comment by pksunkara** [comment]
Basically, any character which is not `;`, ` `, `⁏` and `\n` is a part of the comment. You don't need to set separate syntax for it.

The regex loop is doing exactly that, it is removing all characters other than above 4.

**Comment by pksunkara** [comment]
Can you please fix it accordingly?

**Comment by rdebath** [comment]
Okay, it's "comments" are now back to the previous method, though this does make comment lines problematic, you basically have to add actual commands to hide the newlines.

**Comment by pksunkara** [comment]
Hmm.. Yeah, it looks weird. How about we use `//` to denote a line which is a comment? I don't want to use `;` as you did in the earlier commit.

**Comment by rdebath** [comment]
`//` would be fine by me; though personally I thought `;  ` (with two required spaces!) really fit the language better. I did consider `   ` too (three required spaces) but that seemed too easy. :smile:

**Comment by pksunkara** [comment]
I think a comment starting with a semicolon in this language can be
confusing.

Pavan Kumar Sunkara

**Comment by rdebath** [comment]
Heh heh, it's that the whole point!

**Comment by pksunkara** [comment]
Thanks for the PR :smile:

**Comment by rdebath** [comment]
I forgot to mention, while I was doing the translation I noticed that you have the arguments to the "sub", "div" and "mod" operators (the other "binops" too but it doesn't matter for them) the opposite way round to whitespace despite *everything* else looking the same. Is this intentional ?

**Comment by pksunkara** [comment]
Yes, it was intentional.

**Pull request merged**
